### ISSUE TITLE
Create ScreenManager usage examples

### ISSUE THREAD

**Issue by clergetm** [MathysC/ScreenManager#12]
# TODO
- [ ] #19
- [x] Create a few examples of other projects using ScreenManager
- [x] Add a page in the wiki of example
    - [x] a project in a visual studio solution.
